Repository Bumblebee-Bee/Room-it_BE, pull requests merged in 2025-01, with the labels that each got.

#3 Refactor #1 연관관계 구조개선
  README.md
  src/main/java/roomit/main/domain/reservation/entity/Reservation.java
  src/main/java/roomit/main/domain/review/entity/Review.java
  src/main/java/roomit/main/domain/studyroom/entity/StudyRoom.java
  src/main/java/roomit/main/domain/workplace/entity/Workplace.java
Labels: 🔨 Refactor

#7 Refactor #6 사업자 수정 동적 쿼리
  build.gradle
  src/main/java/roomit/main/domain/business/repository/BusinessRepository.java
  src/main/java/roomit/main/domain/business/repository/search/BusinessDuplicateChecker.java
  src/main/java/roomit/main/domain/business/repository/search/SearchBusiness.java
  src/main/java/roomit/main/domain/business/repository/search/SearchBusinessImpl.java
  src/main/java/roomit/main/domain/business/service/BusinessService.java
  src/main/java/roomit/main/domain/studyroom/repository/search/SearchStudyRoomImpl.java
Labels: 🔨 Refactor

#13 Refactor #10 사업장 crud 수정
  src/main/java/roomit/main/domain/workplace/repository/search/WorkplaceDuplicateChecker.java
  src/main/java/roomit/main/domain/workplace/repository/search/WorkplaceSearch.java
  src/main/java/roomit/main/domain/workplace/repository/search/WorkplaceSearchImpl.java
  src/main/java/roomit/main/domain/workplace/service/GeoService.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/error/ErrorCode.java
  src/main/java/roomit/main/global/util/GeoUtils.java
Labels: 🔨 Refactor

#14 🔨 Build : CI/CD Job 분리 및 일부 수정
  .github/workflows/CI-CD.yml
Labels: 🌏 Deploy

#15 Refactor #12 member crud
  http/member.http
  http/sub.http
  src/main/java/roomit/main/domain/member/controller/MemberController.java
  src/main/java/roomit/main/domain/member/repository/MemberRepository.java
  src/main/java/roomit/main/domain/member/repository/search/MemberDuplicateChecker.java
  src/main/java/roomit/main/domain/member/repository/search/SearchMember.java
  src/main/java/roomit/main/domain/member/repository/search/SearchMemberImpl.java
  src/main/java/roomit/main/domain/member/service/MemberService.java
  src/main/java/roomit/main/domain/notification/controller/NotificationController.java
  src/main/java/roomit/main/domain/notification/service/MemberNotificationService.java
  src/main/java/roomit/main/domain/notification/service/NotificationService.java
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
  src/main/java/roomit/main/global/error/ErrorCode.java
  src/test/java/roomit/main/domain/member/service/MemberServiceTest.java
Labels: 🔨 Refactor

#17 Refactor #6 리뷰 삭제 관련 리팩토링
  src/main/java/roomit/main/domain/business/service/BusinessService.java
  src/main/java/roomit/main/domain/reservation/entity/Reservation.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
  src/main/java/roomit/main/domain/studyroom/service/StudyRoomService.java
Labels: 🔨 Refactor

#18 Refactor #16 알림 리팩토링
  src/main/java/roomit/main/domain/notification/entity/MemberNotification.java
  src/main/java/roomit/main/domain/notification/entity/Notification.java
  src/main/java/roomit/main/domain/notification/entity/ReviewNotification.java
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
Labels: 🔨 Refactor

#24 ♻️ Refactor : 이미지 단일 삭제 메서드 추가
  src/main/java/roomit/main/global/controller/FileController.java
  src/main/java/roomit/main/global/service/FileLocationService.java
Labels: 🔨 Refactor

#27 Feature #5 chat count
  src/main/java/roomit/main/domain/chat/chatmessage/controller/ChatController.java
  src/main/java/roomit/main/domain/chat/chatmessage/listener/ChatEventListener.java
  src/main/java/roomit/main/domain/chat/chatmessage/repository/ChatMessageRepository.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
  src/main/java/roomit/main/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/roomit/main/domain/chat/chatroom/event/ChatRoomConnectEvent.java
  src/main/java/roomit/main/domain/chat/chatroom/event/ChatRoomDisConnectEvent.java
  src/main/java/roomit/main/domain/chat/chatroom/listener/ChatRoomEventListener.java
  src/main/java/roomit/main/domain/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/roomit/main/domain/chat/chatroom/service/ChatRoomRedisService.java
  src/main/java/roomit/main/domain/chat/chatroom/service/ChatRoomService.java
  src/main/java/roomit/main/global/config/async/AsyncConfig.java
  src/main/java/roomit/main/global/config/chat/StompInterceptor.java
Labels: 🔨 Refactor

#29 채팅 접속 알림 리팩토링
  src/main/java/roomit/main/domain/chat/chatmessage/dto/response/ChatConnectResponse.java
  src/main/java/roomit/main/domain/chat/chatroom/listener/ChatRoomEventListener.java
Labels: 🔨 Refactor

#30 채팅 동시 접속 메시지 발행
  src/main/java/roomit/main/domain/chat/chatmessage/dto/response/ChatConnectResponse.java
  src/main/java/roomit/main/domain/chat/chatroom/listener/ChatRoomEventListener.java
Labels: 🔨 Refactor

#31 채팅 읽음 처리
  src/main/java/roomit/main/domain/chat/chatmessage/entity/ChatMessage.java
  src/main/java/roomit/main/domain/chat/chatmessage/repository/ChatMessageRepository.java
Labels: 🐞 BugFix

#32 채팅 읽음 처리 버그픽스
  src/main/java/roomit/main/domain/chat/chatmessage/entity/ChatMessage.java
  src/main/java/roomit/main/domain/chat/chatmessage/repository/ChatMessageRepository.java
Labels: 🐞 BugFix

#33 :wrench: BugFix : 채팅 wss 수정 및 에러코드 수정
  src/main/java/roomit/main/global/config/chat/WebSocketConfig.java
  src/main/java/roomit/main/global/error/ErrorCode.java
Labels: 🐞 BugFix

#34 채팅 wss 수정 및 에러코드 수정
  src/main/java/roomit/main/global/config/chat/WebSocketConfig.java
  src/main/java/roomit/main/global/error/ErrorCode.java
Labels: 🐞 BugFix

#36 채팅 wss security 수정
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/token/config/JWTFilter.java
Labels: 🐞 BugFix

#41 채팅 ws security 수정
  src/main/java/roomit/main/global/config/chat/StompInterceptor.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
Labels: 🐞 BugFix

#42 채팅 ws security 수정
  src/main/java/roomit/main/global/config/chat/StompInterceptor.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
Labels: 🐞 BugFix
